// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Probes that establish what the rest of the harness is allowed to assume.
//!
//! # The font-sensitivity question
//!
//! Reading `parley/src/layout/data.rs` suggests `ClusterData::text_len` is `char::len_utf8()` of a
//! single source char, unconditionally — shaping picks glyphs and advances, but does not decide how
//! many bytes a cluster spans. If true, cursor motion and deletion measure the same whether or not
//! a font covers the script, and the harness needs no Devanagari/Thai/Hangul/CJK font assets.
//!
//! That is a claim about behavior, so it is measured rather than believed:
//! [`traversal_cluster_ranges_are_font_invariant`] compares a tier that shapes Arabic against one
//! that does not, and [`traversal_clusters_tile_the_text`] checks the one-cluster-per-char claim
//! across the whole corpus. **These gate all font work**: only a `text_range` that actually moves
//! could justify vendoring font assets.
//!
//! # The trap this module also pins
//!
//! A layout with no resolvable font has zero clusters, and every traversal API then falls back to a
//! whole-text index — so a test written against it passes for *any* input. That is not
//! hypothetical: see [`traversal_cursor_test_helper_produces_clusters`].

use std::fmt::Write;

use crate::test_name;
use crate::util::TestEnv;

use super::corpus::CORPUS;
use super::env::{FontTier, TraversalEnv};
use super::measure::{ClusterTable, Trajectory};
use super::ops::Op;

/// Thai text with no spaces. Only a dictionary segmenter finds word boundaries inside it.
const THAI_WORDS: &str = "\u{0E44}\u{0E21}\u{0E48}\u{0E44}\u{0E14}\u{0E49}\u{0E01}\u{0E34}\u{0E19}";

/// The `is_word_boundary` bitvector of [`THAI_WORDS`], as `1`/`0` per cluster.
///
/// The fingerprint of which ICU word segmenter is compiled in. Font-independent: `is_word_boundary`
/// comes from analysis, not shaping.
pub(crate) fn segmenter_fingerprint(env: &mut TraversalEnv) -> String {
    ClusterTable::measure(&env.layout(THAI_WORDS))
        .rows
        .iter()
        .map(|r| if r.is_word_boundary { '1' } else { '0' })
        .collect()
}

/// Which segmenter is **actually** in the build, measured rather than read off `cfg!`.
///
/// This is deliberately not `cfg!(feature = "complex-scripts")`. Cargo feature unification means a
/// `--workspace --all-features` build turns on `parley/complex-scripts` whether or not
/// `parley_tests` forwards it, so `cfg!` here can disagree with the library under test — and then
/// a golden would be written under the wrong name and silently pass. Deriving the label from
/// behaviour cannot drift: only a dictionary segmenter finds word boundaries inside unspaced Thai.
pub(crate) fn measured_axis(env: &mut TraversalEnv) -> &'static str {
    let fingerprint = segmenter_fingerprint(env);
    // The leading boundary at index 0 is always set; internal ones mean dictionary segmentation.
    if fingerprint.chars().skip(1).any(|c| c == '1') {
        "complex"
    } else {
        "simple"
    }
}

/// Records what the segmenter axis actually resolved to.
///
/// Its own golden, so the axis is visible rather than inferred, and so a change in ICU's Thai
/// dictionary shows up as a diff here rather than as an unexplained move in a behaviour table.
#[test]
fn traversal_segmenter_axis() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(FontTier::Bundled);

    let axis = measured_axis(&mut t);
    let fingerprint = segmenter_fingerprint(&mut t);

    let mut out = String::new();
    writeln!(&mut out, "# Segmenter axis").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "Generated by `traversal_segmenter_axis`. Do not edit; run `PARLEY_TEST=accept cargo test \
         -p parley_tests traversal`."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`parley`'s `complex-scripts` feature switches ICU between dictionary and non-complex word \
         and line breaking for Thai, CJK, Khmer, Lao and Myanmar. CI runs `--all-features`, so the \
         `complex` setting is the one upstream tests; a plain `cargo test -p parley_tests` gets \
         `simple`, which had no coverage at all before this."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "The label is **measured, not read off `cfg!`**: feature unification can turn on \
         `parley/complex-scripts` whether or not `parley_tests` forwards it, so a `cfg!` here can \
         disagree with the library under test. Only a dictionary segmenter finds word boundaries \
         inside unspaced Thai, so the fingerprint below decides the label and cannot drift from \
         reality."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "- axis: **{axis}**").unwrap();
    writeln!(
        &mut out,
        "- `cfg!(feature = \"complex-scripts\")` in `parley_tests`: {}",
        cfg!(feature = "complex-scripts")
    )
    .unwrap();
    writeln!(
        &mut out,
        "- `is_word_boundary` over `{}`: `{}`",
        THAI_WORDS
            .chars()
            .map(|c| format!("U+{:04X}", c as u32))
            .collect::<Vec<_>>()
            .join(" "),
        fingerprint
    )
    .unwrap();

    env.check_text_snapshot(&format!("traversal/segmenter_axis__{axis}.md"), &out);
}

/// Only word-granular operations may depend on the segmenter axis.
///
/// `complex-scripts` switches ICU between dictionary and non-complex **word and line** breaking, so
/// character-granular motion and deletion must be identical either way. That is a claim about
/// behaviour, so it is checked rather than assumed — and it is what justifies giving only
/// `press_counts` and `motion_steps` an axis suffix while the other six goldens carry none.
///
/// If this fails, an unsuffixed golden has become axis-dependent and will flap between a local
/// `cargo test` and CI's `--all-features` run.
#[test]
fn traversal_axis_affects_word_ops_only() {
    let mut t = TraversalEnv::new(FontTier::Bundled);
    let axis = measured_axis(&mut t);

    // Character-granular press counts, which must not move with the axis. Recorded here as the
    // values measured under *both* settings; if the two ever diverge, one of these fails.
    for e in CORPUS {
        for op in [Op::MoveRight, Op::MoveLeft, Op::Delete, Op::Backdelete] {
            let traj = Trajectory::measure(&mut t, e.text, op);
            assert_eq!(
                traj.presses,
                e.text.chars().count(),
                "{} @ {}: {} took {} presses for {} codepoints. Character-granular operations are \
                 codepoint-granular in parley and must not depend on the `complex-scripts` \
                 segmenter, which only switches word and line breaking. If this changed, the \
                 unsuffixed goldens are now axis-dependent and will flap between a local run and \
                 CI's --all-features run.",
                e.id,
                axis,
                op.slug(),
                traj.presses,
                e.text.chars().count(),
            );
        }
    }
}

/// Diffs cluster structure between a tier that shapes Arabic and one that does not.
///
/// `LatinOnly` (Roboto) versus `Bundled` (Roboto + Noto Kufi Arabic) is a genuine shaping
/// difference, not a cosmetic one: the bundled tier ligates lam-alef into a single glyph, which is
/// exactly the case where a naive model would expect cluster boundaries to move.
#[test]
fn traversal_font_sensitivity() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut latin = TraversalEnv::new(FontTier::LatinOnly);
    let mut bundled = TraversalEnv::new(FontTier::Bundled);
    let mut none = TraversalEnv::new(FontTier::NoFonts);

    let mut out = String::new();
    writeln!(&mut out, "# Font sensitivity of cluster structure").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "Generated by `traversal_font_sensitivity`. Do not edit; run `PARLEY_TEST=accept cargo \
         test -p parley_tests traversal`."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "Compares each corpus entry laid out with **Roboto only** against the same entry laid out \
         with **Roboto + Noto Kufi Arabic**. That is a real shaping difference: the bundled tier \
         ligates Arabic lam-alef into one glyph. `yes` means the projection is identical either way."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`ranges_same` is the one that matters: `Cluster::text_range()` is what every cursor, \
         selection and delete operation reads. If it is font-invariant, those operations can be \
         measured without vendoring font assets for scripts the test fonts do not cover."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`no_fonts` is the cluster count with **nothing registered at all** — a degenerate state in \
         which traversal has nothing to walk and silently reports a whole-text index for every \
         query."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "| id | clusters latin/bundled/no_fonts | ranges_same | flags_same | glyph_len_same | \
         zero_advance_same |"
    )
    .unwrap();
    writeln!(&mut out, "|---|---|---|---|---|---|").unwrap();

    let mut ranges_differ = Vec::new();
    let mut glyphs_differ = Vec::new();

    for e in CORPUS {
        let l = ClusterTable::measure(&latin.layout(e.text));
        let b = ClusterTable::measure(&bundled.layout(e.text));
        let n = ClusterTable::measure(&none.layout(e.text));

        let ranges_same = l.ranges() == b.ranges();
        let same_len = l.rows.len() == b.rows.len();
        let flags_same = same_len
            && l.rows.iter().zip(&b.rows).all(|(x, y)| {
                x.is_word_boundary == y.is_word_boundary
                    && x.is_emoji == y.is_emoji
                    && x.is_hard_line_break == y.is_hard_line_break
                    && x.is_soft_line_break == y.is_soft_line_break
                    && x.is_ligature_start == y.is_ligature_start
                    && x.is_ligature_continuation == y.is_ligature_continuation
                    && x.is_rtl == y.is_rtl
            });
        let glyph_len_same = same_len
            && l.rows
                .iter()
                .zip(&b.rows)
                .all(|(x, y)| x.glyph_len == y.glyph_len);
        let zero_advance_same = same_len
            && l.rows
                .iter()
                .zip(&b.rows)
                .all(|(x, y)| x.zero_advance == y.zero_advance);

        if !ranges_same {
            ranges_differ.push(e.id);
        }
        if !glyph_len_same {
            glyphs_differ.push(e.id);
        }

        writeln!(
            &mut out,
            "| {} | {}/{}/{} | {} | {} | {} | {} |",
            e.id,
            l.rows.len(),
            b.rows.len(),
            n.rows.len(),
            yn(ranges_same),
            yn(flags_same),
            yn(glyph_len_same),
            yn(zero_advance_same),
        )
        .unwrap();
    }

    writeln!(&mut out).unwrap();
    writeln!(&mut out, "## Result").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`text_range` differs between the two shaping tiers for **{} of {} entries**{}",
        ranges_differ.len(),
        CORPUS.len(),
        if ranges_differ.is_empty() {
            String::from(
                ". Cluster text ranges are font-invariant, so cursor motion, selection and \
                 deletion are measurable for every entry with the fonts already in tree — \
                 including the scripts none of them cover. Vendoring font assets would not change \
                 any of those measurements.",
            )
        } else {
            format!(
                ": {}. Those entries need a covering font before their traversal measurements can \
                 be trusted.",
                ranges_differ.join(", ")
            )
        }
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`glyph_len` differs for {} of {} entries{} — the expected shape of a font mattering at \
         all: it changes what is drawn, not what is traversed.",
        glyphs_differ.len(),
        CORPUS.len(),
        if glyphs_differ.is_empty() {
            String::new()
        } else {
            format!(" ({})", glyphs_differ.join(", "))
        }
    )
    .unwrap();

    env.check_text_snapshot("traversal/font_sensitivity.md", &out);
}

fn yn(b: bool) -> &'static str {
    if b { "yes" } else { "**NO**" }
}

/// The claim the rest of the harness rests on.
///
/// If this fails, measurements for scripts the bundled fonts do not cover stop being trustworthy
/// and font assets become mandatory. Worth failing loudly rather than letting a golden diff bury it.
#[test]
fn traversal_cluster_ranges_are_font_invariant() {
    let mut latin = TraversalEnv::new(FontTier::LatinOnly);
    let mut bundled = TraversalEnv::new(FontTier::Bundled);

    for e in CORPUS {
        let l = ClusterTable::measure(&latin.layout(e.text));
        let b = ClusterTable::measure(&bundled.layout(e.text));
        assert_eq!(
            l.ranges(),
            b.ranges(),
            "{}: cluster text ranges differ between a tier that shapes Arabic and one that does \
             not. The harness assumes shaping cannot change how many bytes a cluster spans \
             (text_len = char::len_utf8() per source char). If that is no longer true, \
             measurements for scripts the bundled fonts do not cover are no longer trustworthy.",
            e.id
        );
    }
}

/// Every source char produces exactly one cluster, and the clusters tile the text.
///
/// A char with no cluster is unreachable by every traversal API. The suspect path is the
/// ligature-component loop in `data.rs`, which breaks on `Whitespace::Space`.
#[test]
fn traversal_clusters_tile_the_text() {
    for tier in FontTier::MEASURABLE {
        let mut env = TraversalEnv::new(*tier);
        for e in CORPUS {
            let table = ClusterTable::measure(&env.layout(e.text));
            assert_eq!(
                table.covered_bytes(),
                e.text.len(),
                "{} @ {}: clusters cover {} bytes but the text is {} bytes; some char produced no \
                 cluster and is unreachable by traversal",
                e.id,
                tier.slug(),
                table.covered_bytes(),
                e.text.len(),
            );
            assert_eq!(
                table.rows.len(),
                e.text.chars().count(),
                "{} @ {}: expected exactly one cluster per source char",
                e.id,
                tier.slug(),
            );
            for r in &table.rows {
                assert!(
                    e.text.is_char_boundary(r.range.start) && e.text.is_char_boundary(r.range.end),
                    "{} @ {}: cluster range {:?} is not on char boundaries",
                    e.id,
                    tier.slug(),
                    r.range,
                );
            }
        }
    }
}

/// A layout with no resolvable font has no clusters, and traversal reports a whole-text index for
/// every query rather than failing.
///
/// This is the trap that makes a cursor test vacuous: with expected and actual both computed via
/// `Cursor::from_byte_index`, both collapse to the same fallback and the assertion cannot fail for
/// any input. Pinned here so the harness can never quietly acquire it.
#[test]
fn traversal_no_fonts_yields_no_clusters() {
    let mut env = TraversalEnv::new(FontTier::NoFonts);
    let text = "\u{0061}\u{0062}\u{0063}";
    let layout = env.layout(text);
    let table = ClusterTable::measure(&layout);
    assert_eq!(
        table.rows.len(),
        0,
        "expected an unresolvable font to yield no clusters; if parley gained a last-resort font \
         this is no longer the trap it was, and `traversal_cursor_test_helper_produces_clusters` \
         should be revisited"
    );

    // The silent part: distinct byte indices collapse to the same cursor.
    let a = parley::Cursor::from_byte_index(&layout, 0, parley::Affinity::Downstream);
    let b = parley::Cursor::from_byte_index(&layout, 2, parley::Affinity::Downstream);
    assert_eq!(
        a.index(),
        b.index(),
        "with no clusters, byte 0 and byte 2 must collapse to the same fallback index — this is \
         why a test built on such a layout passes for any input"
    );
}

/// `CursorTest::single_line` must produce clusters.
///
/// It pushes no `FontFamily`, and `create_font_context` registers no system fonts, so nothing
/// resolves and the helper yields zero clusters. Every cursor test built on it then compares two
/// copies of the same fallback index and passes regardless of what the code does.
///
/// Verified by mutation: replacing the expected needles in `cursor_next_visual` and
/// `cursor_previous_visual` with deliberately wrong ones leaves both tests passing.
///
/// `#[ignore]` because it documents a known upstream defect rather than guarding this harness —
/// the harness does not use `CursorTest`. Run with `--ignored` to check whether it is still
/// present; when it starts passing, the fix has landed.
#[test]
#[ignore = "documents a known defect in CursorTest; run with --ignored to check if it is fixed"]
fn traversal_cursor_test_helper_produces_clusters() {
    use crate::util::CursorTest;
    use crate::util::env::create_font_context;
    use parley::LayoutContext;

    let (mut lcx, mut fcx) = (LayoutContext::new(), create_font_context());
    let text = "Lorem ipsum";
    let helper = CursorTest::single_line(text, &mut lcx, &mut fcx);
    let table = ClusterTable::measure(helper.layout());
    assert_eq!(
        table.rows.len(),
        text.chars().count(),
        "CursorTest::single_line produced {} clusters for {} chars. It pushes no FontFamily and \
         create_font_context registers no system fonts, so no font resolves and the layout has no \
         runs. Cursor tests built on it compare two copies of the same whole-text fallback index \
         and cannot fail.",
        table.rows.len(),
        text.chars().count(),
    );
}
