// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! The generated behavior tables.
//!
//! Every cell here is emitted by running code. Nothing in this module encodes an expectation about
//! what parley *should* do — the goldens record what it does, and divergence from the ICU oracle is
//! computed rather than asserted.
//!
//! This is the module that produces the press-count column that PR #693 got wrong by reading the
//! source instead of running it.

use std::fmt::Write;

use crate::test_name;
use crate::util::TestEnv;

use super::corpus::CORPUS;
use super::env::{FontTier, TraversalEnv};
use super::hit::HitTable;
use super::measure::{CursorDelta, Outcome, StepTable, Termination, Trajectory, render_codepoints};
use super::ops::Op;
use super::orphans::OrphanSearch;
use super::probe::measured_axis;
use super::reference::{egc_boundaries, egc_count};

/// The tier every behavior table is measured at.
///
/// One tier, not both: `traversal_cluster_ranges_are_font_invariant` establishes that cluster text
/// ranges do not move between tiers, so measuring twice would produce two identical tables.
const TIER: FontTier = FontTier::Bundled;

fn header(out: &mut String, title: &str, generator: &str) {
    writeln!(out, "# {title}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Generated by `{generator}`. Do not edit; run `PARLEY_TEST=accept cargo test -p \
         parley_tests traversal`."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Measured with the `{}` font tier. Buffers are rendered as codepoints, never as text.",
        TIER.slug()
    )
    .unwrap();
    writeln!(out).unwrap();
}

/// Presses to traverse or erase each corpus entry, per operation.
///
/// **This is the deliverable table.** `egc` is what a whole-grapheme operation would take, `cps` is
/// what a per-codepoint one would take, and the measured column says which — if either — parley
/// implements.
#[test]
fn traversal_press_counts() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Presses to traverse or erase one entry",
        "traversal_press_counts",
    );
    writeln!(
        &mut out,
        "Each operation is applied repeatedly from its natural starting point (start of text for \
         forward operations, end for backward ones) until it stops changing anything."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "- `cps` — codepoints. What a per-codepoint operation costs.\n\
         - `egc` — UAX #29 extended grapheme clusters. What a whole-grapheme operation costs.\n\
         - The remaining columns are **measured**. A count equal to `cps` where `cps > egc` means \
           the operation is codepoint-granular and the user pays the difference."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    let ops = Op::ALL;
    write!(&mut out, "| id | cps | egc |").unwrap();
    for op in ops {
        write!(&mut out, " {} |", op.slug()).unwrap();
    }
    writeln!(&mut out).unwrap();
    write!(&mut out, "|---|---|---|").unwrap();
    for _ in ops {
        write!(&mut out, "---|").unwrap();
    }
    writeln!(&mut out).unwrap();

    for e in CORPUS {
        let cps = e.text.chars().count();
        let egc = egc_count(e.text);
        write!(&mut out, "| {} | {} | {} |", e.id, cps, egc).unwrap();
        for op in ops {
            let traj = Trajectory::measure(&mut t, e.text, *op);
            let cell = match &traj.termination {
                Termination::Converged => traj.presses.to_string(),
                Termination::Stuck { at } => format!("{} **STUCK@{}**", traj.presses, at),
                Termination::Cycle => format!("{} **CYCLE**", traj.presses),
                Termination::Diverged => String::from("**DIVERGED**"),
                Termination::Panicked { at_step, .. } => format!("**PANIC@{at_step}**"),
            };
            write!(&mut out, " {cell} |").unwrap();
        }
        writeln!(&mut out).unwrap();
    }

    // Summaries a reader can check the table against without re-adding a column by hand.
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "## Summary").unwrap();
    writeln!(&mut out).unwrap();
    for op in [Op::Backdelete, Op::Delete, Op::MoveRight, Op::MoveLeft] {
        let mut matches_cps = 0;
        let mut matches_egc = 0;
        let mut neither = 0;
        let mut contested = 0;
        for e in CORPUS {
            let cps = e.text.chars().count();
            let egc = egc_count(e.text);
            if cps == egc {
                continue; // Uninteresting: both models agree.
            }
            contested += 1;
            let traj = Trajectory::measure(&mut t, e.text, op);
            if traj.presses == cps {
                matches_cps += 1;
            } else if traj.presses == egc {
                matches_egc += 1;
            } else {
                neither += 1;
            }
        }
        writeln!(
            &mut out,
            "- **`{}`**: of the {contested} entries where the two models disagree, parley matches \
             per-codepoint on {matches_cps}, per-grapheme on {matches_egc}, and neither on \
             {neither}.",
            op.slug(),
        )
        .unwrap();
    }

    let axis = measured_axis(&mut t);
    env.check_text_snapshot(&format!("traversal/press_counts__{axis}.md"), &out);
}

/// parley's backspace against every reference rule, on every corpus entry.
///
/// **The artifact the PR #693 discussion needs.** Each rule is executed rather than quoted, so
/// "what would Android do here" is measured. `authorities_agree` is the payoff: it separates rows
/// where the references genuinely conflict *with each other* — a legitimate design dispute, where
/// parley picking a side is a choice — from rows where they agree and **parley alone differs**,
/// which is simply a bug.
#[test]
fn traversal_backspace_vs_authorities() {
    use super::rules::Rule;

    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Backspace: parley against every reference rule",
        "traversal_backspace_vs_authorities",
    );
    writeln!(
        &mut out,
        "Presses to erase each entry with backspace. Every column is executed, not quoted. The \
         reference rules are **clean-room reimplementations from documented behaviour** — parley \
         is Apache-2.0 OR MIT and the sources they describe are Apache-2.0 only, so their code \
         cannot be copied here. They are good enough for whole-sequence-versus-one-codepoint, and \
         no more: see `rules.rs` for what is approximate."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "- `egc` — UAX #29 extended grapheme clusters. `CodeMirror` 6 is exactly this.\n\
         - `aosp` — Android, as ported by xi-editor and xilem #303.\n\
         - `blink` — Chrome. AOSP's rule with `Extended_Pictographic` instead of `Emoji`.\n\
         - `pango` — GTK. Script-dependent.\n\
         - `qt` — Qt's `QTextCursor` (QtGui), which backs `QTextEdit`, `QPlainTextEdit` and QML `TextEdit`. NOT `QLineEdit`, a separate implementation that was not examined.\n\
         - `agree` — whether all five references give the same answer.\n\
         - `verdict` — how parley relates to them."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "⚠ **`crlf` appears as a conflict only because of an unverified approximation.** Qt \
         documents no CRLF case — its rule is emoji-or-one-codepoint and nothing else — so the `qt` \
         column splits the pair while the other four do not. Whether real Qt behaves that way was \
         not confirmed; a `QTextDocument` normalises newlines, so the case may never arise there. \
         Do not read that row as evidence about Qt."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "| id | parley | egc | aosp | blink | pango | qt | agree | parley sides with | verdict |"
    )
    .unwrap();
    writeln!(&mut out, "|---|---|---|---|---|---|---|---|---|---|").unwrap();

    let mut agreed_and_parley_differs = Vec::new();
    let mut references_conflict = Vec::new();
    let mut parley_in_minority = Vec::new();

    for e in CORPUS {
        if e.text.is_empty() {
            continue;
        }
        let parley = Trajectory::measure(&mut t, e.text, Op::Backdelete).presses;
        let refs: Vec<usize> = Rule::ALL.iter().map(|r| r.presses(e.text)).collect();
        let agree = refs.iter().all(|r| *r == refs[0]);

        let siding: Vec<&str> = Rule::ALL
            .iter()
            .zip(&refs)
            .filter(|(_, r)| **r == parley)
            .map(|(rule, _)| rule.slug())
            .collect();

        // The most popular answer among the references, and how many gave it. "The references
        // conflict" is too coarse on its own: a 4-1 split with parley on the 1 is a very different
        // claim from parley siding with a majority.
        let mut best_val = refs[0];
        let mut best_n = 0;
        for candidate in &refs {
            let n = refs.iter().filter(|r| *r == candidate).count();
            if n > best_n {
                best_n = n;
                best_val = *candidate;
            }
        }
        let is_minority = !agree && parley != best_val && best_n * 2 > refs.len();

        let verdict = if agree {
            if parley == refs[0] {
                "match"
            } else {
                agreed_and_parley_differs.push(e.id);
                "**parley alone differs**"
            }
        } else {
            references_conflict.push(e.id);
            if is_minority {
                parley_in_minority.push((e.id, parley, best_val, best_n));
                "**minority**"
            } else if siding.is_empty() {
                "**matches none**"
            } else {
                "sides with majority"
            }
        };

        write!(&mut out, "| {} | {} |", e.id, parley).unwrap();
        for r in &refs {
            write!(&mut out, " {r} |").unwrap();
        }
        writeln!(
            &mut out,
            " {} | {} | {} |",
            if agree { "yes" } else { "**no**" },
            if siding.is_empty() {
                String::from("none")
            } else {
                siding.join(",")
            },
            verdict
        )
        .unwrap();
    }

    writeln!(&mut out).unwrap();
    writeln!(&mut out, "## Summary").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "**References agree and parley differs — {} entr{}**{}",
        agreed_and_parley_differs.len(),
        if agreed_and_parley_differs.len() == 1 {
            "y"
        } else {
            "ies"
        },
        if agreed_and_parley_differs.is_empty() {
            String::from(
                ". There is no input on which every reference implementation agrees and parley \
                 does something else.",
            )
        } else {
            format!(
                ": {}. These are not a matter of opinion — every reference agrees and parley does \
                 something else.",
                agreed_and_parley_differs.join(", ")
            )
        }
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "**References conflict with each other — {} entries.** On most of these parley sides with \
         the majority, so it is picking a side in a genuine disagreement rather than being wrong.",
        references_conflict.len(),
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "**Of those, parley is in the minority on {} — the rows worth a second look**, because \
         \"the references disagree\" is a much weaker defence when most of them agree with each \
         other and not with parley:",
        parley_in_minority.len()
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    if parley_in_minority.is_empty() {
        writeln!(&mut out, "(none)").unwrap();
    } else {
        writeln!(&mut out, "| id | parley | majority | majority size |").unwrap();
        writeln!(&mut out, "|---|---|---|---|").unwrap();
        for (id, parley, val, n) in &parley_in_minority {
            writeln!(&mut out, "| {id} | {parley} | {val} | {n} of 5 |").unwrap();
        }
    }

    env.check_text_snapshot("traversal/backspace_vs_authorities.md", &out);
}

/// What backspace and forward delete actually remove, press by press.
///
/// The press count alone cannot show *which* codepoints were taken, and "deletes the whole emoji"
/// versus "deletes the last codepoint of the emoji" are the same number for a two-codepoint
/// sequence. This table shows the buffer after every press.
#[test]
fn traversal_delete_trajectories() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Delete and backdelete, press by press",
        "traversal_delete_trajectories",
    );
    writeln!(
        &mut out,
        "The buffer after each press. `backdelete` starts at the end of the text, `delete` at the \
         start. A sequence that is supposed to be indivisible should go to `(empty)` in one step."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    for e in CORPUS {
        if e.text.is_empty() {
            continue;
        }
        writeln!(&mut out, "### {}", e.id).unwrap();
        writeln!(&mut out).unwrap();
        writeln!(&mut out, "`{}`", render_codepoints(e.text)).unwrap();
        writeln!(&mut out).unwrap();
        for op in [Op::Backdelete, Op::Delete] {
            let traj = Trajectory::measure(&mut t, e.text, op);
            writeln!(
                &mut out,
                "- **{}** ({} presses, {:?}):",
                op.slug(),
                traj.presses,
                traj.termination
            )
            .unwrap();
            for (i, step) in traj.steps.iter().enumerate() {
                writeln!(&mut out, "  {}. `{}`", i + 1, step.buffer).unwrap();
            }
        }
        writeln!(&mut out).unwrap();
    }

    env.check_text_snapshot("traversal/delete_trajectories.md", &out);
}

/// Every caret motion, from every position.
///
/// A trajectory from one end is blind to a step that misbehaves in the middle. This sweeps the
/// whole function graph.
#[test]
fn traversal_motion_steps() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Caret motion from every position",
        "traversal_motion_steps",
    );
    writeln!(
        &mut out,
        "Each operation applied **once** from every char boundary. Cells are `focus@affinity` \
         (`D`ownstream/`U`pstream), or `anchor-focus@affinity` for a range."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`*` marks a step that changed nothing; `~` marks one that changed only the affinity. \
         Affinity is not swept — the public driver API cannot place a caret at a chosen affinity, \
         so `from` shows what `move_to_byte` snapped to."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    for e in CORPUS {
        if e.text.is_empty() {
            continue;
        }
        writeln!(&mut out, "### {}", e.id).unwrap();
        writeln!(&mut out).unwrap();
        write!(&mut out, "| from |").unwrap();
        for op in Op::MOTION {
            write!(&mut out, " {} |", op.slug()).unwrap();
        }
        writeln!(&mut out).unwrap();
        write!(&mut out, "|---|").unwrap();
        for _ in Op::MOTION {
            write!(&mut out, "---|").unwrap();
        }
        writeln!(&mut out).unwrap();

        let tables: Vec<StepTable> = Op::MOTION
            .iter()
            .map(|op| StepTable::measure(&mut t, e.text, *op))
            .collect();

        for (i, row) in tables[0].rows.iter().enumerate() {
            write!(&mut out, "| {} |", row.from_state.render()).unwrap();
            for table in &tables {
                let cell = match &table.rows[i].outcome {
                    Outcome::Motion { to, delta } => match delta {
                        CursorDelta::Moved => to.render(),
                        CursorDelta::AffinityOnlyFlip => format!("~{}", to.render()),
                        CursorDelta::Stationary => format!("*{}", to.render()),
                    },
                    Outcome::Edit { .. } => String::from("(edit)"),
                    Outcome::Panicked(m) => format!("**PANIC: {m}**"),
                };
                write!(&mut out, " {cell} |").unwrap();
            }
            writeln!(&mut out).unwrap();
        }
        writeln!(&mut out).unwrap();
    }

    let axis = measured_axis(&mut t);
    env.check_text_snapshot(&format!("traversal/motion_steps__{axis}.md"), &out);
}

/// Where a click can put the caret.
///
/// Every other table here sweeps the keyboard. This one sweeps the pointer, which is a separate
/// reachability question: `Cursor::from_point` is not implemented in terms of the motion ops and
/// can land somewhere they never do.
///
/// **The column that matters is `mid_egc`**: caret positions a click can reach that are *not*
/// grapheme boundaries — i.e. the places a user can put the caret inside one of their characters
/// by clicking. `no_ink` counts how many of those sit beside a codepoint with no visual form, where
/// there is nothing on screen to suggest the position exists.
///
/// # No segmenter axis
///
/// Unlike `traversal_press_counts` and `traversal_motion_steps`, this golden has no
/// `__simple`/`__complex` suffix: hit testing reads cluster advances and never `is_word_boundary`,
/// and the layout is built with wrapping off so line breaking cannot pull the dictionary in either.
/// **Measured, not assumed** — the golden is byte-identical with and without `complex-scripts`. If
/// that ever stops being true this test fails under `--all-features`, which is the correct outcome:
/// it means hit testing grew a segmenter dependency worth knowing about.
#[test]
fn traversal_click_reachability() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Where a click can put the caret",
        "traversal_click_reachability",
    );
    writeln!(
        &mut out,
        "`Cursor::from_point` at points derived from every cluster's measured advance — each \
         cluster is probed at fractions of its own width, never on an absolute pixel grid, so the \
         table depends on the layout's structure and not on the font's exact metrics. \
         `PlainEditor::move_to_point` and `Selection::from_point` both delegate here, so this is \
         the click path."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "- `bounds` — cluster boundaries: the caret positions that exist.\n\
         - `hit` — how many of them some click actually produces.\n\
         - `mid_egc` — **reachable positions that are not UAX #29 grapheme boundaries.** Each one \
           is a place a click puts the caret inside a user-perceived character.\n\
         - `no_ink` — of those, how many are adjacent to a codepoint with no visual form of its \
           own (ZWJ, a variation selector, a combining mark, a tag character).\n\
         - `slices` — whether the clusters covering one shaped glyph all report the same advance. \
           `equal` is how a codepoint with no width of its own still gets a clickable region."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    let mut total_mid_egc = 0;
    let mut total_no_ink = 0;
    let mut entries_all_reachable = 0;
    let mut entries_measured = 0;
    let mut no_ink_with_width = Vec::new();

    writeln!(
        &mut out,
        "| id | cps | bounds | hit | mid_egc | no_ink | slices |"
    )
    .unwrap();
    writeln!(&mut out, "|---|---|---|---|---|---|---|").unwrap();

    for e in CORPUS {
        if e.text.is_empty() {
            continue;
        }
        entries_measured += 1;
        let table = HitTable::measure(&mut t, e.text);
        let bounds = table.boundaries();
        let hit = table.reachable_indices();
        let egc: Vec<usize> = egc_boundaries(e.text);

        let mid: Vec<usize> = hit.iter().copied().filter(|i| !egc.contains(i)).collect();
        // A position is "no-ink adjacent" if the cluster starting or ending there has no visual
        // form of its own.
        let no_ink: Vec<usize> = mid
            .iter()
            .copied()
            .filter(|i| {
                table.clusters.iter().any(|c| {
                    (c.range.start == *i || c.range.end == *i) && c.ink.is_undisplayable_alone()
                })
            })
            .collect();

        if bounds.iter().all(|b| hit.contains(b)) {
            entries_all_reachable += 1;
        }
        total_mid_egc += mid.len();
        total_no_ink += no_ink.len();

        for c in &table.clusters {
            if c.ink.is_undisplayable_alone() && !c.zero_advance {
                no_ink_with_width.push((e.id, c.range.clone(), c.ink.slug()));
            }
        }

        writeln!(
            &mut out,
            "| {} | {} | {} | {} | {} | {} | {} |",
            e.id,
            e.text.chars().count(),
            bounds.len(),
            hit.len(),
            mid.len(),
            no_ink.len(),
            match table.equal_slices {
                None => "n/a",
                Some(true) => "equal",
                Some(false) => "**unequal**",
            }
        )
        .unwrap();
    }

    writeln!(&mut out).unwrap();
    writeln!(&mut out, "## Per entry").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`ink` is what the cluster's codepoint renders as **on its own**, from Unicode — not a \
         measurement of parley. `zero_adv` is parley's advance for it. A row with a no-ink class \
         and `zero_adv = no` is a codepoint that draws nothing yet owns a clickable region."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    for e in CORPUS {
        if e.text.chars().count() < 2 {
            continue;
        }
        let table = HitTable::measure(&mut t, e.text);
        let egc: Vec<usize> = egc_boundaries(e.text);

        writeln!(&mut out, "### {}", e.id).unwrap();
        writeln!(&mut out).unwrap();
        writeln!(&mut out, "`{}`", render_codepoints(e.text)).unwrap();
        writeln!(&mut out).unwrap();
        writeln!(&mut out, "| cluster | ink | zero_adv | lig | glyphs |").unwrap();
        writeln!(&mut out, "|---|---|---|---|---|").unwrap();
        for c in &table.clusters {
            writeln!(
                &mut out,
                "| {}..{} | {} | {} | {} | {} |",
                c.range.start,
                c.range.end,
                c.ink.slug(),
                if c.zero_advance { "**yes**" } else { "no" },
                c.lig,
                c.glyphs,
            )
            .unwrap();
        }
        writeln!(&mut out).unwrap();

        writeln!(&mut out, "| position | egc bound | reachable by click |").unwrap();
        writeln!(&mut out, "|---|---|---|").unwrap();
        for b in table.boundaries() {
            let affs: Vec<&str> = table
                .reachable
                .iter()
                .filter(|p| p.index == b)
                .map(|p| p.affinity)
                .collect();
            writeln!(
                &mut out,
                "| {} | {} | {} |",
                b,
                if egc.contains(&b) { "yes" } else { "**no**" },
                if affs.is_empty() {
                    String::from("**never**")
                } else {
                    affs.join(",")
                }
            )
            .unwrap();
        }
        writeln!(&mut out).unwrap();
    }

    writeln!(&mut out, "## Summary").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "- Every cluster boundary is reachable by some click on **{entries_all_reachable} of \
         {entries_measured}** entries.\n\
         - **{total_mid_egc}** reachable caret positions across the corpus are not grapheme \
           boundaries: a click puts the caret inside a user-perceived character.\n\
         - **{total_no_ink}** of those are adjacent to a codepoint with no visual form of its own.\n\
         - **{}** clusters hold a codepoint that renders nothing on its own, yet were given a \
           non-zero — therefore clickable — advance.",
        no_ink_with_width.len()
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    if !no_ink_with_width.is_empty() {
        writeln!(&mut out, "| id | cluster | ink |").unwrap();
        writeln!(&mut out, "|---|---|---|").unwrap();
        for (id, range, class) in &no_ink_with_width {
            writeln!(
                &mut out,
                "| {} | {}..{} | {} |",
                id, range.start, range.end, class
            )
            .unwrap();
        }
    }

    env.check_text_snapshot("traversal/click_reachability.md", &out);
}

/// Graphemes that `delete`/`backdelete` can strand with nothing to render.
///
/// A breadth-first search over **every** buffer the two ops can reach from every caret position,
/// so a "no" here means no sequence of presses produces one, not that the sequence tried did not.
/// Every witness is shortest-first.
///
/// The case this exists for: a buffer holding a lone U+200D. It is non-empty, the caret can sit
/// either side of it, arrow keys spend a press crossing it — and there is nothing on screen.
///
/// No segmenter axis, for the same measured reason as [`traversal_click_reachability`]: `delete`
/// and `backdelete` are codepoint-granular and consult no word segmenter, and the golden is
/// byte-identical with and without `complex-scripts`. The word-deletion variants, which *would*
/// depend on it, are deliberately out of scope — see `orphans.rs`.
#[test]
fn traversal_orphaned_graphemes() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Graphemes that editing can strand with nothing to render",
        "traversal_orphaned_graphemes",
    );
    writeln!(
        &mut out,
        "Breadth-first search over every buffer reachable from the entry by `delete` and \
         `backdelete` at any caret position. A grapheme is **orphaned** when every codepoint left \
         in it has no visual form of its own — a lone ZWJ, a lone variation selector, a lone tag \
         character. The buffer is not empty and the caret still has to cross it, but the user sees \
         nothing there."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "- `states` — distinct buffers reachable. The search is exhaustive over them.\n\
         - `orphans` — distinct undisplayable graphemes found across all of them.\n\
         - `classes` — how many distinct *kinds* those fall into. The per-entry tables list one \
           example of each kind rather than every combination; see `orphans.rs`.\n\
         - `presses` — length of the **shortest** press sequence that produces one. `0` means the \
           entry already contained one before any editing, which is a property of the corpus and \
           not of parley.\n\
         - Whitespace is not an orphan: a lone newline or tab is an ordinary buffer.\n\
         - Word-deletion variants are out of scope; see `orphans.rs`."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    let mut with_orphans = Vec::new();
    let mut created_by_editing = Vec::new();
    let mut one_press = Vec::new();
    let mut any_truncated = false;

    writeln!(
        &mut out,
        "| id | cps | states | orphans | classes | presses |"
    )
    .unwrap();
    writeln!(&mut out, "|---|---|---|---|---|---|").unwrap();

    let mut details = String::new();

    for e in CORPUS {
        if e.text.is_empty() {
            continue;
        }
        let search = OrphanSearch::run(&mut t, e.text);
        any_truncated |= search.truncated;

        let shortest = search.by_class.iter().map(|o| o.witness.len()).min();
        if !search.by_class.is_empty() {
            with_orphans.push(e.id);
            if search.by_class.iter().any(|o| !o.witness.is_empty()) {
                created_by_editing.push(e.id);
            }
            if shortest == Some(1) {
                one_press.push(e.id);
            }
        }

        writeln!(
            &mut out,
            "| {} | {} | {} | {} | {} | {} |",
            e.id,
            e.text.chars().count(),
            search.states,
            search.distinct,
            search.by_class.len(),
            match shortest {
                None => String::from("-"),
                Some(n) => n.to_string(),
            }
        )
        .unwrap();

        if search.by_class.is_empty() {
            continue;
        }
        writeln!(&mut details, "### {}", e.id).unwrap();
        writeln!(&mut details).unwrap();
        writeln!(&mut details, "`{}`", render_codepoints(e.text)).unwrap();
        writeln!(&mut details).unwrap();
        if search.distinct > search.by_class.len() {
            writeln!(
                &mut details,
                "{} distinct orphans, grouped into {} kinds; one shortest-witness example each.",
                search.distinct,
                search.by_class.len()
            )
            .unwrap();
            writeln!(&mut details).unwrap();
        }
        writeln!(
            &mut details,
            "| classes | example | resulting buffer | shortest witness |"
        )
        .unwrap();
        writeln!(&mut details, "|---|---|---|---|").unwrap();
        for o in &search.by_class {
            writeln!(
                &mut details,
                "| {} | `{}` | `{}` | {} |",
                o.classes,
                o.egc,
                o.buffer,
                o.render_witness()
            )
            .unwrap();
        }
        writeln!(&mut details).unwrap();
    }

    writeln!(&mut out).unwrap();
    writeln!(&mut out, "## Per entry").unwrap();
    writeln!(&mut out).unwrap();
    if details.is_empty() {
        writeln!(
            &mut out,
            "(no entry can be left holding an invisible grapheme)"
        )
        .unwrap();
        writeln!(&mut out).unwrap();
    } else {
        out.push_str(&details);
    }

    writeln!(&mut out, "## Summary").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "- **{} entries** can hold a grapheme with nothing to render.\n\
         - **{} of those reach one by editing** — the original text did not contain it, and \
           `delete`/`backdelete` produced it: {}.\n\
         - **{} need a single press** to strand one: {}.",
        with_orphans.len(),
        created_by_editing.len(),
        if created_by_editing.is_empty() {
            String::from("(none)")
        } else {
            created_by_editing.join(", ")
        },
        one_press.len(),
        if one_press.is_empty() {
            String::from("(none)")
        } else {
            one_press.join(", ")
        }
    )
    .unwrap();
    if any_truncated {
        writeln!(&mut out).unwrap();
        writeln!(
            &mut out,
            "⚠ **The state cap bound.** The search was not exhaustive; see `MAX_STATES`."
        )
        .unwrap();
    }

    env.check_text_snapshot("traversal/orphaned_graphemes.md", &out);
}
