// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! The generated behavior tables.
//!
//! Every cell here is emitted by running code. Nothing in this module encodes an expectation about
//! what parley *should* do — the goldens record what it does, and divergence from the ICU oracle is
//! computed rather than asserted.
//!
//! This is the module that produces the press-count column that PR #693 got wrong by reading the
//! source instead of running it.

use std::fmt::Write;

use crate::test_name;
use crate::util::TestEnv;

use super::corpus::CORPUS;
use super::env::{FontTier, TraversalEnv};
use super::measure::{CursorDelta, Outcome, StepTable, Termination, Trajectory, render_codepoints};
use super::ops::Op;
use super::reference::egc_count;

/// The tier every behavior table is measured at.
///
/// One tier, not both: `traversal_cluster_ranges_are_font_invariant` establishes that cluster text
/// ranges do not move between tiers, so measuring twice would produce two identical tables.
const TIER: FontTier = FontTier::Bundled;

fn header(out: &mut String, title: &str, generator: &str) {
    writeln!(out, "# {title}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Generated by `{generator}`. Do not edit; run `PARLEY_TEST=accept cargo test -p \
         parley_tests traversal`."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Measured with the `{}` font tier. Buffers are rendered as codepoints, never as text.",
        TIER.slug()
    )
    .unwrap();
    writeln!(out).unwrap();
}

/// Presses to traverse or erase each corpus entry, per operation.
///
/// **This is the deliverable table.** `egc` is what a whole-grapheme operation would take, `cps` is
/// what a per-codepoint one would take, and the measured column says which — if either — parley
/// implements.
#[test]
fn traversal_press_counts() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Presses to traverse or erase one entry",
        "traversal_press_counts",
    );
    writeln!(
        &mut out,
        "Each operation is applied repeatedly from its natural starting point (start of text for \
         forward operations, end for backward ones) until it stops changing anything."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "- `cps` — codepoints. What a per-codepoint operation costs.\n\
         - `egc` — UAX #29 extended grapheme clusters. What a whole-grapheme operation costs.\n\
         - The remaining columns are **measured**. A count equal to `cps` where `cps > egc` means \
           the operation is codepoint-granular and the user pays the difference."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    let ops = Op::ALL;
    write!(&mut out, "| id | cps | egc |").unwrap();
    for op in ops {
        write!(&mut out, " {} |", op.slug()).unwrap();
    }
    writeln!(&mut out).unwrap();
    write!(&mut out, "|---|---|---|").unwrap();
    for _ in ops {
        write!(&mut out, "---|").unwrap();
    }
    writeln!(&mut out).unwrap();

    for e in CORPUS {
        let cps = e.text.chars().count();
        let egc = egc_count(e.text);
        write!(&mut out, "| {} | {} | {} |", e.id, cps, egc).unwrap();
        for op in ops {
            let traj = Trajectory::measure(&mut t, e.text, *op);
            let cell = match &traj.termination {
                Termination::Converged => traj.presses.to_string(),
                Termination::Stuck { at } => format!("{} **STUCK@{}**", traj.presses, at),
                Termination::Cycle => format!("{} **CYCLE**", traj.presses),
                Termination::Diverged => String::from("**DIVERGED**"),
                Termination::Panicked { at_step, .. } => format!("**PANIC@{at_step}**"),
            };
            write!(&mut out, " {cell} |").unwrap();
        }
        writeln!(&mut out).unwrap();
    }

    // Summaries a reader can check the table against without re-adding a column by hand.
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "## Summary").unwrap();
    writeln!(&mut out).unwrap();
    for op in [Op::Backdelete, Op::Delete, Op::MoveRight, Op::MoveLeft] {
        let mut matches_cps = 0;
        let mut matches_egc = 0;
        let mut neither = 0;
        let mut contested = 0;
        for e in CORPUS {
            let cps = e.text.chars().count();
            let egc = egc_count(e.text);
            if cps == egc {
                continue; // Uninteresting: both models agree.
            }
            contested += 1;
            let traj = Trajectory::measure(&mut t, e.text, *&op);
            if traj.presses == cps {
                matches_cps += 1;
            } else if traj.presses == egc {
                matches_egc += 1;
            } else {
                neither += 1;
            }
        }
        writeln!(
            &mut out,
            "- **`{}`**: of the {contested} entries where the two models disagree, parley matches \
             per-codepoint on {matches_cps}, per-grapheme on {matches_egc}, and neither on \
             {neither}.",
            op.slug(),
        )
        .unwrap();
    }

    env.check_text_snapshot("traversal/press_counts.md", &out);
}

/// What backspace and forward delete actually remove, press by press.
///
/// The press count alone cannot show *which* codepoints were taken, and "deletes the whole emoji"
/// versus "deletes the last codepoint of the emoji" are the same number for a two-codepoint
/// sequence. This table shows the buffer after every press.
#[test]
fn traversal_delete_trajectories() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Delete and backdelete, press by press",
        "traversal_delete_trajectories",
    );
    writeln!(
        &mut out,
        "The buffer after each press. `backdelete` starts at the end of the text, `delete` at the \
         start. A sequence that is supposed to be indivisible should go to `(empty)` in one step."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    for e in CORPUS {
        if e.text.is_empty() {
            continue;
        }
        writeln!(&mut out, "### {}", e.id).unwrap();
        writeln!(&mut out).unwrap();
        writeln!(&mut out, "`{}`", render_codepoints(e.text)).unwrap();
        writeln!(&mut out).unwrap();
        for op in [Op::Backdelete, Op::Delete] {
            let traj = Trajectory::measure(&mut t, e.text, op);
            writeln!(
                &mut out,
                "- **{}** ({} presses, {:?}):",
                op.slug(),
                traj.presses,
                traj.termination
            )
            .unwrap();
            for (i, step) in traj.steps.iter().enumerate() {
                writeln!(&mut out, "  {}. `{}`", i + 1, step.buffer).unwrap();
            }
        }
        writeln!(&mut out).unwrap();
    }

    env.check_text_snapshot("traversal/delete_trajectories.md", &out);
}

/// Every caret motion, from every position.
///
/// A trajectory from one end is blind to a step that misbehaves in the middle. This sweeps the
/// whole function graph.
#[test]
fn traversal_motion_steps() {
    let mut env = TestEnv::new(test_name!(), None);
    let mut t = TraversalEnv::new(TIER);

    let mut out = String::new();
    header(
        &mut out,
        "Caret motion from every position",
        "traversal_motion_steps",
    );
    writeln!(
        &mut out,
        "Each operation applied **once** from every char boundary. Cells are `focus@affinity` \
         (`D`ownstream/`U`pstream), or `anchor-focus@affinity` for a range."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "`*` marks a step that changed nothing; `~` marks one that changed only the affinity. \
         Affinity is not swept — the public driver API cannot place a caret at a chosen affinity, \
         so `from` shows what `move_to_byte` snapped to."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    for e in CORPUS {
        if e.text.is_empty() {
            continue;
        }
        writeln!(&mut out, "### {}", e.id).unwrap();
        writeln!(&mut out).unwrap();
        write!(&mut out, "| from |").unwrap();
        for op in Op::MOTION {
            write!(&mut out, " {} |", op.slug()).unwrap();
        }
        writeln!(&mut out).unwrap();
        write!(&mut out, "|---|").unwrap();
        for _ in Op::MOTION {
            write!(&mut out, "---|").unwrap();
        }
        writeln!(&mut out).unwrap();

        let tables: Vec<StepTable> = Op::MOTION
            .iter()
            .map(|op| StepTable::measure(&mut t, e.text, *op))
            .collect();

        for (i, row) in tables[0].rows.iter().enumerate() {
            write!(&mut out, "| {} |", row.from_state.render()).unwrap();
            for table in &tables {
                let cell = match &table.rows[i].outcome {
                    Outcome::Motion { to, delta } => match delta {
                        CursorDelta::Moved => to.render(),
                        CursorDelta::AffinityOnlyFlip => format!("~{}", to.render()),
                        CursorDelta::Stationary => format!("*{}", to.render()),
                    },
                    Outcome::Edit { .. } => String::from("(edit)"),
                    Outcome::Panicked(m) => format!("**PANIC: {m}**"),
                };
                write!(&mut out, " {cell} |").unwrap();
            }
            writeln!(&mut out).unwrap();
        }
        writeln!(&mut out).unwrap();
    }

    env.check_text_snapshot("traversal/motion_steps.md", &out);
}
